### PR TITLE
Fix warnings on .NET SDK 6.0 and VS 2022

### PR DESCRIPTION
**Pull request by idg10**
Changes to the default settings for analyzers in .NET SDK 6.0 meant that anyone trying to build reaqtor with the latest SDK would see a huge number of warnings and errors. This gets us back to a clean build at the command line, and also an absence of code analyzer messages if opening the project in Visual Studio 2022 (which requires more changes than are needed for a clean command line build).

The code still builds without warnings or errors on .NET SDK 5.0, and opens cleanly in Visual Studio 2019.

### CODE REVIEW

**Comment by idg10** [comment]
@bartdesmet, this PR is currently in draft because there are a couple of places in the code that continue to provoke analyzer warnings that look to me like they might be flagging genuine issues.

The first is at https://github.com/reaqtive/reaqtor/blob/85f6f05e895bbcd9397a2145ac4e934e5a16b830/Reaqtor/Core/Engine/Reaqtor.QueryEngine/Reaqtor/QueryEngine/Edges/OutputEdge.cs#L81

The analyzer complains that this field is set but never read from. It is used in exactly one place:

https://github.com/reaqtive/reaqtor/blob/85f6f05e895bbcd9397a2145ac4e934e5a16b830/Reaqtor/Core/Engine/Reaqtor.QueryEngine/Reaqtor/QueryEngine/Edges/OutputEdge.cs#L111-L115

So we hold onto this subscription, but never do anything with it. Should we be disposing the external subscription at some point, and if not, should we just remove this field?


The second is a similar "field set but never read" in the remoting testing framework:

https://github.com/reaqtive/reaqtor/blob/85f6f05e895bbcd9397a2145ac4e934e5a16b830/Reaqtor/Samples/Remoting/Reaqtor.Remoting.TestingFramework/TestClient/TestReactivePlatformClient.cs#L32

Is there missing code that should be cleaning up? Or is there nothing that needs doing here and so we should just remove the field?

**Comment by bartdesmet** [comment]
The edge subscription stuff can use a `_` discard. IIRC, we put it in a field to make dump debugging easier.

The cleanup environment stuff can be removed. That's a remnant of some more sophistication in the Remoting stack but it got stale after we added more roles (messaging, state store, etc.).

**Comment by idg10** [comment]
It does look like the environment cleanup needs to happen: I tried disabling it completely, and although running all tests concerned individually worked, if I run all the tests, I get failures—presumably there's some parallel execution going on here?

The behaviour in place was to run the cleanup even when it wasn't requested. I've modified it in the "Make TestReactivePlatformClient honour cleanupEnvironment " commit so that it runs cleanup when requested, and doesn't otherwise, and tests seem to be passing with that (but were failing with cleanup completely disabled). So is it OK to stick with that change?

(I see all the builds are now failing. But I think that might be environmental. It's failing on the "Install NBGV tool check, which is before we even get to compiling the code, so I don't think it's caused by this change. The commit from a couple of days ago worked, and I'd be surprised if this latest one caused that.)

**Comment by idg10** [comment]
(The same NBGV error occurred on January 13th, and then went away again. If it manages a clean build again I'll leave that for now and fix it in a separate PR. But if it persists, I'll have to fix that before we can close this I guess.)

**Review by HowardvanRooijen — APPROVED** [review]
👌

**Pull request merged**
